version: "3.8"
services:
  expense:
    container_name: expenseapi
    restart: always
    image: dipjyotimetia/expenseapi
    ports:
      - "3001:3001"
    links:
      - mongodb

  account:
    container_name: accountapi
    restart: always
    image: dipjyotimetia/accountapi
    ports:
      - "3002:3002"
    links:
      - mongodb

  mongodb:
    container_name: mongodb
    image: mongo:3.6.21
    environment: 
      - MONGO_INITDB_DATABASE=testdb
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata:      